apiVersion: v1
kind: Secret
metadata:
  name: {{ include "express-openapi-boilerplate.fullname" . }}
  labels:
{{ include "express-openapi-boilerplate.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
