openapi: 3.0.0
info:
  title: express-openapi sample project
  version: '3.0.0'
paths:
  /users:
    get:
      description: Get users
      operationId: getUsers
      responses:
        200:
          description: An echo of the request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  age:
                    type: integer
                  isCool:
                    type: boolean
