openapi: 3.0.0
info:
  title: express-openapi sample project
  version: '3.0.1'
paths:
  /files:
    get:
      description: Get files
      operationId: getFiles
      responses:
        200:
          description: Fetch file list from S3 bucket
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    Key:
                      type: string
                    LastModified:
                      type: string
                    ETag:
                      type: string
                    Size:
                      type: string
                    StorageClass:
                      type: string
        500:
          description: Unable to fetch file list from S3 bucket
